apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sonarqube-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - secrets
  - routes
  verbs:
  - create
  - update
  - delete
  - get
  - list
  - watch
  - patch
- apiGroups:
  - gpte.opentlc.com
  resources:
  - sonarqubes
  verbs:
  - create
  - update
  - delete
  - get
  - list
  - watch
  - patch
